version: '3.3'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./postgres/postgres.env
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: ./django
    restart: always
    env_file:
      - ./django/django.env
    ports:
      - '8000'
    volumes:
      - ./django/src:/project:Z
    depends_on:
      - postgres


volumes:
  pgdata:
  pgadmin:
