version: '3.3'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./postgres/postgres.env
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: ./django
    restart: always
    env_file:
      - ./django/django.env
    command: python /prj/d0/manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./django/src:/prj:Z


volumes:
  pgdata:
